import React, { useState, useRef } from 'react';
import { analyzeCSV } from '../api/plotSense';

export default function PlotSensePanel() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const inputRef = useRef(null);

  const handleFile = (f) => {
    if (!f || !f.name.endsWith('.csv')) {
      setError('Please upload a valid .csv file.');
      return;
    }
    setFile(f);
    setError(null);
    setResult(null);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    const f = e.dataTransfer.files[0];
    if (f) handleFile(f);
  };

  const handleAnalyze = async () => {
    if (!file) return;
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const data = await analyzeCSV(file);
      setResult(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Upload Zone */}
      <div
        className={`upload-zone ${file ? 'has-file' : ''}`}
        onClick={() => inputRef.current?.click()}
        onDrop={handleDrop}
        onDragOver={e => e.preventDefault()}
      >
        <span className="upload-icon">{file ? '✅' : '📂'}</span>
        <span className="upload-text">
          {file ? file.name : 'Drop your CSV here or click to browse'}
        </span>
        <span className="upload-sub">
          {file
            ? `${(file.size / 1024).toFixed(1)} KB · Ready to analyze`
            : 'Supports .csv files only'}
        </span>
        <input
          ref={inputRef}
          type="file"
          accept=".csv"
          style={{ display: 'none' }}
          onChange={e => handleFile(e.target.files[0])}
        />
      </div>

      <div className="flex items-center gap-2">
        <button
          className="btn btn-primary"
          onClick={handleAnalyze}
          disabled={!file || loading}
        >
          {loading ? <><span className="spinner" /> Analyzing…</> : '🚀 Generate Analytics'}
        </button>
        {file && !loading && (
          <button className="btn btn-secondary" onClick={() => { setFile(null); setResult(null); setError(null); }}>
            Clear
          </button>
        )}
      </div>

      {error && (
        <div style={{ padding: '12px 16px', background: 'rgba(248,113,113,0.1)', border: '1px solid var(--danger)', borderRadius: 'var(--radius-sm)', color: 'var(--danger)', fontSize: 14 }}>
          ⚠️ {error}
        </div>
      )}

      {result && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          {/* Dataset Info + Recommendations */}
          <div className="insights-grid">
            <div className="insight-box">
              <h4>📋 Dataset Info</h4>
              <pre>{result.datasetInfo || 'No info returned.'}</pre>
            </div>
            <div className="insight-box">
              <h4>📈 Chart Recommendations</h4>
              <pre>{result.recommendationsText || 'No recommendations.'}</pre>
            </div>
          </div>

          {/* AI Insights */}
          <div className="card">
            <div className="card-header">
              <div className="card-title"><div className="card-icon">🤖</div>AI Insights</div>
            </div>
            <div className="card-body">
              <pre style={{ whiteSpace: 'pre-wrap', fontSize: 14, lineHeight: 1.7, color: 'var(--text)' }}>
                {result.aiInsights || 'No insights returned.'}
              </pre>
            </div>
          </div>

          {/* Plot (Gradio returns a matplotlib figure; we show a placeholder message) */}
          {result.plotFig ? (
            <div className="card">
              <div className="card-header">
                <div className="card-title"><div className="card-icon">📊</div>Generated Chart</div>
              </div>
              <div className="card-body" style={{ textAlign: 'center', color: 'var(--text-muted)', padding: 32 }}>
                {typeof result.plotFig === 'string' && result.plotFig.startsWith('data:') ? (
                  <img src={result.plotFig} alt="Generated chart" style={{ maxWidth: '100%', borderRadius: 8 }} />
                ) : (
                  <p style={{ fontSize: 14 }}>
                    Chart generated by PlotSense. View it in the PlotSense Gradio interface
                    or extend the API wrapper to return a PNG data URL.
                  </p>
                )}
              </div>
            </div>
          ) : null}
        </div>
      )}

      {!result && !loading && !error && (
        <div className="card">
          <div className="card-body" style={{ textAlign: 'center', padding: '40px 24px', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>📊</div>
            <p style={{ fontSize: 15, fontWeight: 600, color: 'var(--text)' }}>No data yet</p>
            <p style={{ fontSize: 13, marginTop: 4 }}>Upload a CSV file to see AI-generated charts and insights.</p>
          </div>
        </div>
      )}
    </div>
  );
}
